"""new fields in user model

Revision ID: 118859ef885a
Revises: 034889f8b96b
Create Date: 2020-07-14 11:30:29.695127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118859ef885a'
down_revision = '034889f8b96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
