"""followers

Revision ID: 127033f3f54f
Revises: 118859ef885a
Create Date: 2020-07-14 16:09:02.261445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127033f3f54f'
down_revision = '118859ef885a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
